/// Flutter icons Custom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class Custom {
  Custom._();

  static const _kFontFam = 'Custom';

  static const IconData down_open = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData clipboard = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData forward = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData cancel_circled = const IconData(0xf06e, fontFamily: _kFontFam);
  static const IconData food = const IconData(0xf0f5, fontFamily: _kFontFam);
  static const IconData bed = const IconData(0xf236, fontFamily: _kFontFam);
}
